SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
	FROM EMPLOYEES
	WHERE	SALARY IN (SELECT MIN(SALARY)
			   FROM EMPLOYEES
			   GROUP BY DEPARTMENT_ID); 
         SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
	FROM EMPLOYEES
	WHERE (SALARY,DEPARTMENT_ID) 
               IN 
               (SELECT MIN(SALARY),DEPARTMENT_ID
		FROM EMPLOYEES
		GROUP BY DEPARTMENT_ID); 

